remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-menus
title: [II Encontro de Jovens Algebristas]
menus:
  header:
    title: Home
    weight: 1
description: Belo Horizonte, 09-11 de maio de 2023
show_downloads: false
github:
  is_project_page: false
  
